### ISSUE TITLE
Conversion problem with toRomaji function

### ISSUE THREAD

**Issue by Moseco** [jeroen-meijer/kana_kit#18]
When the toRomaji function is given katakana with the pattern "*ヮー" it throws the exception ```Null check operator used on a null value``` on [line 59 of the conversions.dart file](https://github.com/jeroen-meijer/kana_kit/blob/afd454d7447de9da92eceb128edb9cd0a3f3cd26/lib/src/conversions.dart#L59)

Two examples I encountered the problem with [シークヮーサー](https://jisho.org/word/%E3%82%B7%E3%83%BC%E3%82%AF%E3%83%AF%E3%83%BC%E3%82%B5%E3%83%BC) and [シマウヮー](https://jisho.org/word/%E5%B3%B6%E8%B1%9A)

**Comment by Moseco** [comment]
I created a (hopefully) simple fix. I added a check above [line 59 of the conversions.dart](https://github.com/jeroen-meijer/kana_kit/blob/afd454d7447de9da92eceb128edb9cd0a3f3cd26/lib/src/conversions.dart#L59).

```
// Ensure 'ヮー' => 'ゎー' become 'waa'
if (previousKana == 'ゎ' && char == 'ー') {
  hiraChars.removeLast();
  hiraChars.addAll(['わ', 'あ']);
  continue;
}
```

It now converts 'シークヮーサー' to 'shiikuwaasaa' and 'シマウヮー' to 'shimauwaa' which seems correct to me (and for what it's worth Google Translate's pronunciation also does an extended vowel wa).

I tested this on my own and it doesn't seem to mess with any other conversions. Although I wasn't able to run the test suite because pub is having trouble resolving the dependencies. 

@jeroen-meijer What do you think of this change? If it looks okay I can create a PR. If not, do you have a different solution in mind?

**Comment by jeroen-meijer** [comment]
Hey there,

Thanks for opening this issue. Looks great! I'll quickly try it myself later today, and fix the pub CI pipelines and tests in the meantime 👍🏻

**Comment by tdondich** [comment]
Just a ping to see if this will make it in.

**Comment by HighLiuk** [comment]
Hey @jeroen-meijer how about this?
This bug is preventing the [JM Dict package](https://pub.dev/packages/jm_dict) from working

And by the way for those who just simply can't wait for the PR to be merged, just add this to your `pubspec.yaml`:

```yaml
dependency_overrides:
  kana_kit:
    git:
      url: https://github.com/Moseco/kana_kit.git
      ref: master
```

**Comment by jeroen-meijer** [comment]
@HighLiuk Hi there, thanks for pinging me on this. Apologies to @Moseco for not reviewing this in time.

I'll add a test for the edge case that this PR accounts for, then merge and push a new release.
Love that there's more people in the community working on Japanese content :)

**Comment by HighLiuk** [comment]
Thank you @jeroen-meijer! Sure, I love Japanese :)
I'm working on a personal non-commercial project of a flutter app in which you can read your favourite manga with support for text detection and OCR, furigana completion, dictionary and so on.
I already use your package and it's great. But for the dictionary feature I need the JM Dict package to work, so that's why we're here :)

Thank you for the reply. I was worried this project was abandoned.

**Comment by jeroen-meijer** [comment]
That's so cool! Let me know when it's out or if you have any updates :)
HMU @ jeroenfkmeijer@gmail.com

**Comment by jeroen-meijer** [comment]
@HighLiuk I'm almost done preparing the PR with various fixes and updates, including this one.

Do you have two or three test cases I can use to add tests for this edge-case? Wanna make sure I get these right. Thx.

**Comment by HighLiuk** [comment]
@jeroen-meijer as far as I know, the test cases provided by @Moseco are the only (rare) cases:
シークヮーサー
シマウヮー

**Comment by jeroen-meijer** [comment]
@HighLiuk The PR is submitted (#24), but the fix made by @Moseco doesn't actually perform the translation correctly.

I can't work on this for the rest of the day, but feel free to have a look at the PR and propose a fix I can implement instead.

(I added two tests for this edge-case so just run the test suite to see if you fixed it. Good luck!)

**Comment by Moseco** [comment]
@jeroen-meijer I am not sure why it is not working now in your release branch. I will try to investigate today and push a fix.

Edit: initial comment was incorrect about the problem.

**Comment by Moseco** [comment]
@jeroen-meijer I quickly looked at the problem. it seems to correctly convert the rare kana when it is going from katakana to romaji but it does not do it correctly when going from hiragana to romaji. What would the best fix be? To change the hepburn map to account for 'ゎー'?

**Comment by jeroen-meijer** [comment]
@Moseco Done. See #24

**Comment by jeroen-meijer** [comment]
This issue should now be fixed in version 2.1.0, which has [just released](https://pub.dev/packages/kana_kit/versions/2.1.0).

**Comment by jeroen-meijer** [comment]
CC @HighLiuk

**Comment by 14h4i** [comment]
@jeroen-meijer I can't update to 2.1.0 because this issue https://github.com/jeroen-meijer/kana_kit/issues/25
