### ISSUE TITLE
Looser `meta` version constraints

### ISSUE THREAD

**Issue by narumi147** [jeroen-meijer/kana_kit#25]
Not sure `meta` is required to be greater than 1.16.0 for this package, but flutter stable(3.24) is using meta 1.15.0.

So if possible please change the minimal meta version.

**Comment by 14h4i** [comment]
Same problem

**Comment by jeroen-meijer** [comment]
Hi, thanks for the report and the reminder.

I just submitted a PR with a fix: #26. Can you confirm this fixes your issue and report your findings in the comments of the PR? Thanks!
